"use client";

import React, { createContext, useContext, useEffect, useState } from 'react';
import { BRAND_DATA_DIR_EXAMPLE } from '@/lib/brand';

type Language = 'zh' | 'en';

type Translations = {
    [key in Language]: {
        [key: string]: string;
    };
};

const translations: Translations = {
    zh: {
        "login": "登录",
        "username": "用户名",
        "password": "密码",
        "totp": "两步验证码 (可选)",
        "login_loading": "登录中...",
        "login_success": "登录成功",
        "login_failed": "登录失败",
        "user_or_pass_error": "用户名或密码错误",
        "totp_error": "两步验证码错误或已过期",
        "auth_failed": "认证失败，请重新登录",
        "sidebar_home": "首页",
        "sidebar_accounts": "账号管理",
        "sidebar_settings": "系统设置",
        "sidebar_tasks": "任务列表",
        "add_account": "添加账号",
        "add_task": "新增任务",
        "edit": "编辑",
        "run": "运行",
        "delete": "删除",
        "confirm_delete": "确定要删除吗？",
        "save": "保存",
        "cancel": "取消",
        "settings_desc": "一个完全使用 Antigravity 开发的 Telegram 自动发送消息/签到项目",
        "settings_title": "系统设置",
        "logout": "退出登录",
        "connected": "已连接",
        "account_status_checking": "检测中",
        "account_status_invalid": "登录失效",
        "account_status_error": "检测失败",
        "account_relogin_required": "账号状态失效，请重新登录",
        "relogin_account": "重新登录账号",
        "logs": "日志",
        "remove": "移除",
        "edit_account": "编辑账号",
        "remark": "备注 (可选)",
        "remark_placeholder": "如：工作号/备用号",
        "session_name": "账号名称（自定义）",
        "phone_number": "手机号码",
        "login_code": "登录验证码",
        "login_code_placeholder": "Telegram 发送的 5 位数",
        "two_step_pass": "两步验证 (Cloud Password)",
        "two_step_placeholder": "未设置请留空",
        "proxy": "SOCKS5 代理 (可选)",
        "proxy_placeholder": "socks5://ip:port 或 socks5://user:pass@ip:port",
        "confirm_connect": "确认保存",
        "login_method_phone": "验证码登录",
        "login_method_qr": "扫码登录",
        "qr_start": "获取二维码",
        "qr_refresh": "刷新二维码",
        "qr_cancel": "取消扫码",
        "qr_waiting": "等待扫码",
        "qr_scanned": "已扫码待确认",
        "qr_success": "登录成功",
        "qr_failed": "登录失败",
        "qr_expired": "二维码已过期",
        "qr_tip": "打开 Telegram 扫描二维码登录",
        "qr_expires_in": "有效期 {seconds}s",
        "next_step": "下一步",
        "back": "返回",
        "send_code": "发送验证码",
        "safety_verify": "安全验证",
        "code_sent": "验证码已发送至您的手机/Telegram 客户端",
        "running_logs": "运行日志",
        "logs_summary": "最近 {count} 条记录（{days} 天历史）",
        "export_logs": "导出日志",
        "no_logs": "暂无运行日志",
        "task_label": "任务",
        "bot_reply": "机器人回复",
        "task_exec_success": "执行成功",
        "task_exec_failed": "执行失败",
        "close": "关闭",
        "success": "成功",
        "failure": "失败",
        "task_details": "任务详情",
        "manage_tasks_for": "管理账号的所有自动签到任务",
        "refresh_chats": "刷新 Chat 列表",
        "loading": "加载中...",
        "no_tasks": "配置第一个签到目的地",
        "no_tasks_desc": "选择一个频道或群组，设定动作与时间点",
        "create_task": "创建签到任务",
        "edit_task": "编辑任务",
        "task_name": "任务名称",
        "task_name_placeholder": "例如: linuxdo_sign",
        "task_name_required": "请填写任务名称",
        "cron_required": "请填写 CRON 表达式",
        "range_required": "请填写完整的时间段",
        "chat_required": "请至少添加一个 Chat",
        "select_chat_error": "请选择一个 Chat",
        "add_action_error": "请至少添加一个动作",
        "load_failed": "加载失败",
        "account_session_invalid": "账号登录已失效，请重新登录",
        "create_success": "任务创建成功",
        "create_failed": "创建失败",
        "associated_account": "关联账号",
        "define_global_rules": "定义全局签到规则，可以应用到多个目标频道",
        "basic_config": "基本配置",
        "scheduling_mode": "调度模式",
        "random_range_default": "随机时间段 (默认)",
        "random_range_desc": "系统将在设定的时间段内随机选择一个时间点执行任务，避免被检测为机器人。",
        "start_time": "开始时间",
        "end_time": "结束时间",
        "start_label": "开始",
        "end_label": "结束",
        "time_range": "时间范围",
        "target_chat_config": "目标聊天配置",
        "add_chat": "添加聊天",
        "no_target_chat": "尚未添加任何目标频道",
        "actions_count": "动作",
        "id_label": "ID",
        "deploy_task": "立即部署任务",
        "configure_target_chat": "配置目标聊天",
        "select_target_chat": "选择目标聊天",
        "select_chat_placeholder": "请选择服务器中的聊天...",
        "action_sequence_title": "任务动作序列",
        "add_sign_action": "添加签到动作",
        "no_actions_hint": "点击上方按钮添加第一个动作，如发送 \"/checkin\"",
        "confirm_add": "确认添加",
        "random_range_recommend": "随机时间段 (推荐)",
        "fixed_time_cron": "固定时间 (Cron)",
        "sign_time_cron": "签到时间 (Cron 表达式)",
        "cron_example": "示例: 0 9 * * * (早上 9:00)",
        "random_time_hint": "将在该时间段内随机选择执行时间",
        "refresh_list": "刷新列表",
        "refresh_chat_title": "从 Telegram 重新获取对话",
        "select_from_list": "从列表选择...",
        "search_chat": "搜索会话",
        "search_chat_placeholder": "输入名称 / 用户名 / Chat ID",
        "searching": "搜索中...",
        "search_no_results": "未找到匹配会话",
        "ai_vision_mode": "AI 识图模式",
        "ai_logic_solver": "AI 计算模式",
        "ai_vision_click_mode": "AI 识图后点击按钮",
        "ai_vision_send_mode": "AI 识图后发送文本",
        "ai_logic_send_mode": "AI 计算题后发送文本",
        "ai_logic_click_mode": "AI 计算题后点击按钮",
        "sign_time": "签到时间 (CRON)",
        "random_delay": "随机延迟 (分钟)",
        "action_interval": "动作间隔 (毫秒)",
        "select_chat": "选择频道/群组",
        "manual_chat_id": "或手动输入聊天 ID",
        "delete_after": "消息删除延迟 (秒, 可选)",
        "action_sequence": "有序动作序列",
        "deploy_now": "立即部署",
        "save_changes": "保存修改",
        "add_action": "添加动作",
        "change_username": "修改用户名",
        "new_username": "新用户名",
        "current_password": "当前密码",
        "change_password": "修改密码",
        "old_password": "旧密码",
        "new_password": "新密码",
        "confirm_new_password": "确认新密码",
        "2fa_settings": "两步验证 (2FA)",
        "2fa_enable_desc": "启用两步验证将显著提升您的账户安全性。启用后，登录时除了密码外，还需要输入由身份验证器生成的动态代码。",
        "start_setup": "开始设置",
        "scan_qr": "1. 扫描二维码",
        "scan_qr_desc": "使用 Google Authenticator 或其他身份验证器扫描左侧二维码",
        "backup_secret": "2. 备份密钥",
        "verify_code": "验证代码",
        "verify": "验证",
        "disable_2fa": "停用两步验证",
        "ai_config": "AI 模型配置",
        "api_key": "API 密钥",
        "base_url": "基础 URL (Base URL)",
        "model": "预设模型 (Model)",
        "test_connection": "连接测试",
        "global_settings": "全局签到设置",
        "sign_interval": "签到间隔 (秒)",
        "sign_interval_desc": "设置将应用于所有启用全局间隔的任务",
        "log_retention": "日志保留天数",
        "save_global_params": "保存全局参数",
        "tg_api_config": "Telegram API 凭据",
        "restore_default": "恢复默认配置",
        "api_id": "API ID",
        "api_hash": "API Hash",
        "apply_api_config": "应用 API 配置",
        "tg_config_warning": "修改此配置可能导致现有登录会话失效，建议仅在添加账号出现 API 兼容性问题时才进行自定义。",
        "backup_migration": "数据备份与迁移",
        "export_config": "导出全部配置",
        "export_desc": "包含所有任务定义与账号基础信息。注意：此文件包含敏感信息，请妥善保管。",
        "download_json": "下载配置文件 (.json)",
        "import_config": "导入配置内容",
        "paste_json": "在此粘贴 JSON 文本内容...",
        "overwrite_conflict": "覆盖冲突的任务",
        "execute_import": "执行导入",
        "upload_json": "上传 JSON 文件",
        "process_successful": "执行成功",
        "process_error": "执行出错",
        "warning_notice": "警告提示",
        "connect_success": "连接成功",
        "action_send_text": "发送文本",
        "action_send_dice": "发送骰子",
        "action_click_button": "点击按钮",
        "action_ai_vision": "AI 图片识别",
        "action_ai_logic": "AI 计算题",
        "action_ai_vision_click": "AI 识图后点按钮",
        "action_ai_vision_send": "AI 识图后发文本",
        "action_ai_logic_send": "AI 计算后发文本",
        "action_ai_logic_click": "AI 计算后点按钮",
        "placeholder_msg": "发送的消息内容...",
        "placeholder_btn": "要点击的按钮上的文字...",
        "manual_id_placeholder": "手动输入 Chat ID...",
        "delete_after_placeholder": "发送后多久自动删除指令...",
        "no_data": "暂无数据",
        "account_name_phone_required": "请填写账号名称和手机号",
        "account_name_duplicate": "账号名已存在，请更换",
        "send_code_failed": "发送验证码失败",
        "login_code_required": "请输入验证码",
        "account_name_required": "请输入账号名称",
        "verify_failed": "验证失败",
        "confirm_delete_account": "确定要删除账号 {name} 吗？",
        "account_deleted": "账号已删除",
        "delete_failed": "删除失败",
        "save_failed": "保存失败",
        "qr_create_failed": "生成二维码失败",
        "cancel_failed": "取消失败",
        "logs_fetch_failed": "获取日志失败",
        "clear_logs": "清空日志",
        "clear_logs_confirm": "确定要清空账号 {name} 的日志吗？",
        "clear_logs_success": "日志已清空",
        "clear_logs_failed": "清空日志失败",
        "qr_expired_not_found": "二维码已过期或不存在",
        "qr_login_failed": "扫码登录失败",
        "qr_status_failed": "获取扫码状态失败",
        "qr_password_required": "需要两步验证密码",
        "qr_password_missing": "请输入两步验证密码",
        "qr_password_invalid": "两步验证密码错误",
        "qr_password_submit": "提交验证",
        "account_name_placeholder": "例如：Work_Account_01",
        "phone_number_placeholder": "+86 138 0000 0000",
        "qr_alt": "二维码",
        "task_deleted": "任务 {name} 已删除",
        "task_run_failed": "任务运行失败",
        "task_run_success": "任务 {name} 运行成功",
        "account_name_prompt": "请输入账号名称",
        "status_active": "启用",
        "status_paused": "暂停",
        "task_schedule": "执行时间",
        "task_channels": "目标会话",
        "task_hits": "{count} 个会话",
        "task_last_run": "最近执行",
        "task_run_logs_title": "任务运行日志: {name}",
        "task_monitor_title": "任务运行监控: {name}",
        "task_monitor_status": "运行状态",
        "task_monitor_summary": "最新摘要",
        "task_monitor_messages_tab": "消息历史",
        "task_monitor_no_messages": "当前还没有收到结构化消息事件",
        "task_message_event_sent": "发送消息",
        "task_message_event_received": "收到消息",
        "task_message_event_edited": "消息更新",
        "task_history_logs": "任务历史日志",
        "task_history_logs_title": "任务历史日志: {name}",
        "task_history_empty": "暂无历史执行日志",
        "task_history_no_messages": "该次执行没有结构化消息事件（旧记录或本次未收到回包）",
        "task_history_no_flow": "该记录没有流程详情（旧版本可能仅保存结果）",
        "task_history_truncated": "日志过长，已截断。原始行数: {count}",
        "logs_waiting": "等待日志输出...",
        "task_running": "正在运行中...",
        "task_done": "任务执行完成",
        "task_executing": "正在执行...",
        "chats_refreshed": "会话列表已刷新",
        "refresh_failed": "刷新失败",
        "search_failed": "搜索失败",
        "chat_id_numeric": "手动输入的 Chat ID 必须是数字",
        "update_success": "任务更新成功",
        "update_failed": "更新失败",
        "chat_default_name": "会话 {id}",
        "form_incomplete": "请填写完整信息",
        "username_changed": "用户名修改成功",
        "change_failed": "修改失败",
        "password_mismatch": "两次输入的密码不一致",
        "password_changed": "密码修改成功",
        "setup_failed": "准备失败",
        "two_factor_enabled": "两步验证已启用",
        "enable_failed": "启用失败",
        "two_factor_disable_prompt": "请输入两步验证码以停用：",
        "two_factor_disabled": "两步验证已停用",
        "disable_failed": "停用失败",
        "export_success": "配置导出成功",
        "export_failed": "导出失败",
        "import_empty": "请粘贴配置内容",
        "import_success": "导入成功",
        "import_failed": "导入失败",
        "ai_save_success": "AI 配置保存成功",
        "connect_failed": "连接失败",
        "test_failed": "测试出错",
        "confirm_delete_ai": "确定要删除 AI 配置吗？",
        "ai_delete_success": "AI 配置已删除",
        "global_save_success": "全局设置保存成功",
        "telegram_save_success": "Telegram 配置保存成功",
        "confirm_reset_telegram": "确定要重置 Telegram 配置为默认值吗？",
        "config_reset": "配置已重置",
        "operation_failed": "操作失败",
        "new_username_placeholder": "新用户名",
        "current_password_placeholder": "验证当前密码",
        "status_enabled": "已启用",
        "status_disabled": "已停用",
        "totp_code_placeholder": "6 位数字",
        "delete_ai_config": "删除 AI 配置",
        "ai_base_url_placeholder": "https://api.openai.com/v1",
        "api_key_keep_hint": "留空表示保持当前 API 密钥不变",
        "sign_interval_placeholder": "留空则随机 1-120 秒",
        "data_dir": "数据目录",
        "data_dir_placeholder": `例如: ${BRAND_DATA_DIR_EXAMPLE}`,
        "data_dir_desc": "用于保存 sessions、logs、数据库和任务数据",
        "data_dir_restart_hint": "修改后需重启后端服务生效",
        "tg_api_id_placeholder": "来自 my.telegram.org",
        "tg_api_hash_placeholder": "来自 my.telegram.org",
        "telegram_notification_config": "Telegram Bot 通知",
        "telegram_notification_desc": "为任务完成通知配置官方 Telegram Bot。全局配置会作为默认目标，单账号可在编辑弹窗中覆盖或关闭。",
        "notification_bot_token": "Bot Token",
        "notification_bot_token_placeholder": "123456:ABC-DEF",
        "notification_bot_token_keep_hint": "留空并勾选下方选项时，将保留当前 Bot Token",
        "notification_chat_id": "Chat ID",
        "notification_chat_id_placeholder": "例如: -1001234567890",
        "notification_keep_existing_token": "保留现有 Token",
        "telegram_notification_save_success": "Telegram 通知配置保存成功",
        "telegram_notification_test_success": "测试消息已发送，请检查 Telegram",
        "telegram_notification_test_failed": "测试消息发送失败",
        "confirm_delete_telegram_notification": "确定要删除 Telegram 通知配置吗？",
        "telegram_notification_delete_success": "Telegram 通知配置已删除",
        "delete_notification_config": "删除通知配置",
        "test_send": "测试发送",
        "task_notification": "任务完成通知",
        "notification_follow_global": "跟随全局",
        "notification_custom": "自定义",
        "notification_disabled": "关闭通知",
        "github_repo": "GitHub 仓库",
        "unknown_sender": "未知发送者",
        "unknown_chat": "未知会话",
        "totp_placeholder": "留空即跳过",
        "switch_to_english": "切换到英文",
        "switch_to_chinese": "切换到中文",
        "switch_to_light": "切换至日间模式",
        "switch_to_dark": "切换至夜间模式"
    },
    en: {
        "login": "Login",
        "username": "Username",
        "password": "Password",
        "totp": "TOTP Code (Optional)",
        "login_loading": "Logging in...",
        "login_success": "Login Successful",
        "login_failed": "Login Failed",
        "user_or_pass_error": "Invalid username or password",
        "totp_error": "Invalid or expired TOTP code",
        "auth_failed": "Authentication failed, please login again",
        "sidebar_home": "Home",
        "sidebar_accounts": "Accounts",
        "sidebar_settings": "System Settings",
        "sidebar_tasks": "Tasks",
        "add_account": "Add Account",
        "add_task": "Add Task",
        "edit": "Edit",
        "run": "Run",
        "delete": "Delete",
        "confirm_delete": "Are you sure you want to delete?",
        "save": "Save",
        "cancel": "Cancel",
        "settings_desc": "A Telegram auto-sign/messaging project developed entirely using Antigravity",
        "settings_title": "System Settings",
        "logout": "Logout",
        "connected": "Connected",
        "account_status_checking": "Checking",
        "account_status_invalid": "Session Invalid",
        "account_status_error": "Check Failed",
        "account_relogin_required": "Account session is invalid, please re-login",
        "relogin_account": "Re-login Account",
        "logs": "Logs",
        "remove": "Remove",
        "edit_account": "Edit Account",
        "remark": "Remark (Optional)",
        "remark_placeholder": "e.g. Work/Backup",
        "session_name": "Account Name (Custom)",
        "phone_number": "Phone Number",
        "login_code": "Login Code",
        "login_code_placeholder": "5-digit code from Telegram",
        "two_step_pass": "2FA (Cloud Password)",
        "two_step_placeholder": "Leave blank if not set",
        "proxy": "SOCKS5 Proxy (Optional)",
        "proxy_placeholder": "socks5://ip:port or socks5://user:pass@ip:port",
        "confirm_connect": "Confirm Save",
        "login_method_phone": "Code Login",
        "login_method_qr": "QR Login",
        "qr_start": "Get QR",
        "qr_refresh": "Refresh QR",
        "qr_cancel": "Cancel",
        "qr_waiting": "Waiting for scan",
        "qr_scanned": "Scanned, awaiting confirmation",
        "qr_success": "Login success",
        "qr_failed": "Login failed",
        "qr_expired": "QR expired",
        "qr_tip": "Open Telegram and scan the QR code to login",
        "qr_expires_in": "Expires in {seconds}s",
        "next_step": "Next Step",
        "back": "Back",
        "send_code": "Send Code",
        "safety_verify": "Security Verification",
        "code_sent": "Verification code sent to your Phone/Telegram",
        "running_logs": "Running Logs",
        "logs_summary": "Showing last {count} entries ({days} Days History)",
        "export_logs": "Export Logs",
        "no_logs": "No logs available",
        "task_label": "Task",
        "bot_reply": "Bot Reply",
        "task_exec_success": "executed successfully",
        "task_exec_failed": "execution failed",
        "close": "Close",
        "success": "Success",
        "failure": "Failure",
        "task_details": "Task Details",
        "manage_tasks_for": "Manage automatic sign-in tasks for account",
        "refresh_chats": "Refresh Chats",
        "loading": "Loading...",
        "no_tasks": "Configure Your First Task",
        "no_tasks_desc": "Select a channel or group, set actions and timing",
        "create_task": "Create Task",
        "edit_task": "Edit Task",
        "task_name": "Task Name",
        "task_name_placeholder": "e.g. linuxdo_sign",
        "task_name_required": "Please enter a task name",
        "cron_required": "Please enter a CRON expression",
        "range_required": "Please enter a full time range",
        "chat_required": "Please add at least one chat",
        "select_chat_error": "Please select a chat",
        "add_action_error": "Please add at least one action",
        "load_failed": "Load failed",
        "account_session_invalid": "Account session expired, please login again",
        "create_success": "Task created",
        "create_failed": "Create failed",
        "associated_account": "Associated Account",
        "define_global_rules": "Define global sign-in rules that apply to multiple targets",
        "basic_config": "Basic Configuration",
        "scheduling_mode": "Scheduling Mode",
        "random_range_default": "Random Range (Default)",
        "random_range_desc": "The system randomly selects a time within the configured range to avoid bot detection.",
        "start_time": "Start Time",
        "end_time": "End Time",
        "start_label": "Start",
        "end_label": "End",
        "time_range": "Time Range",
        "target_chat_config": "Target Chat Configuration",
        "add_chat": "Add Chat",
        "no_target_chat": "No target chats added yet",
        "actions_count": "Actions",
        "id_label": "ID",
        "deploy_task": "Deploy Task",
        "configure_target_chat": "Configure Target Chat",
        "select_target_chat": "Select Target Chat",
        "select_chat_placeholder": "Select from server chats...",
        "action_sequence_title": "Action Sequence",
        "add_sign_action": "Add Sign Action",
        "no_actions_hint": "Click the button above to add the first action, e.g. \"/checkin\"",
        "confirm_add": "Confirm Add",
        "random_range_recommend": "Random Range (Recommended)",
        "fixed_time_cron": "Fixed Time (Cron)",
        "sign_time_cron": "Sign-in Time (Cron Expression)",
        "cron_example": "Example: 0 9 * * * (9:00 AM)",
        "random_time_hint": "Random execution time within this range",
        "refresh_list": "Refresh",
        "refresh_chat_title": "Re-fetch chats from Telegram",
        "select_from_list": "Select from list...",
        "search_chat": "Search Chats",
        "search_chat_placeholder": "Name / Username / Chat ID",
        "searching": "Searching...",
        "search_no_results": "No matching chats",
        "ai_vision_mode": "AI Vision Mode",
        "ai_logic_solver": "AI Logic Solver",
        "ai_vision_click_mode": "AI Vision Click",
        "ai_vision_send_mode": "AI Vision Send",
        "ai_logic_send_mode": "AI Math Send",
        "ai_logic_click_mode": "AI Math Click",
        "sign_time": "Sign-in Time (CRON)",
        "random_delay": "Random Delay (Minutes)",
        "action_interval": "Action Interval (ms)",
        "select_chat": "Select Channel/Group",
        "manual_chat_id": "Or Manual Chat ID",
        "delete_after": "Message Deletion Delay (Sec, Optional)",
        "action_sequence": "Action Sequence",
        "deploy_now": "Deploy Now",
        "save_changes": "Save Changes",
        "add_action": "Add Action",
        "change_username": "Change Username",
        "new_username": "New Username",
        "current_password": "Current Password",
        "change_password": "Change Password",
        "old_password": "Old Password",
        "new_password": "New Password",
        "confirm_new_password": "Confirm New Password",
        "2fa_settings": "Two-Factor Auth (2FA)",
        "2fa_enable_desc": "Enabling 2FA significantly improves your account security. Once enabled, you will need to enter a dynamic code generated by an authenticator app.",
        "start_setup": "Start Setup",
        "scan_qr": "1. Scan QR Code",
        "scan_qr_desc": "Scan the QR code on the left using Google Authenticator or another app",
        "backup_secret": "2. Backup Secret",
        "verify_code": "Verification Code",
        "verify": "Verify",
        "disable_2fa": "Disable 2FA",
        "ai_config": "AI Model Configuration",
        "api_key": "API Key",
        "base_url": "Base URL",
        "model": "Default Model",
        "test_connection": "Test Connection",
        "global_settings": "Global Sign-in Settings",
        "sign_interval": "Sign-in Interval (Sec)",
        "sign_interval_desc": "Applies to all tasks with global interval enabled",
        "log_retention": "Log Retention (Days)",
        "save_global_params": "Save Global Parameters",
        "tg_api_config": "Telegram API Credentials",
        "restore_default": "Restore Default",
        "api_id": "API ID",
        "api_hash": "API Hash",
        "apply_api_config": "Apply API Config",
        "tg_config_warning": "Changing this may invalidate existing sessions. Only customize if encounter API issues.",
        "backup_migration": "Backup & Migration",
        "export_config": "Export All Config",
        "export_desc": "Contains all tasks and account info. Note: Handle this file with care as it contains sensitive data.",
        "download_json": "Download Config (.json)",
        "import_config": "Import Config Content",
        "paste_json": "Paste JSON content here...",
        "overwrite_conflict": "Overwrite Conflicts",
        "execute_import": "Execute Import",
        "action_send_text": "Send Text",
        "action_send_dice": "Send Dice",
        "action_click_button": "Click Button",
        "action_ai_vision": "AI Image Recognition",
        "action_ai_logic": "AI Math Solver",
        "action_ai_vision_click": "AI Vision Click Button",
        "action_ai_vision_send": "AI Vision Send Text",
        "action_ai_logic_send": "AI Math Send Text",
        "action_ai_logic_click": "AI Math Click Button",
        "placeholder_msg": "Message to send...",
        "placeholder_btn": "Text on button to click...",
        "manual_id_placeholder": "Manual Chat ID...",
        "delete_after_placeholder": "Auto-delete delay after sending...",
        "no_data": "No Data",
        "account_name_phone_required": "Please fill in account name and phone number",
        "account_name_duplicate": "Account name already exists. Please change it.",
        "send_code_failed": "Failed to send code",
        "login_code_required": "Please enter code",
        "account_name_required": "Please enter account name",
        "verify_failed": "Verification failed",
        "confirm_delete_account": "Are you sure you want to delete account {name}?",
        "account_deleted": "Account deleted",
        "delete_failed": "Delete failed",
        "save_failed": "Save failed",
        "qr_create_failed": "Failed to create QR",
        "cancel_failed": "Cancel failed",
        "logs_fetch_failed": "Failed to get logs",
        "clear_logs": "Clear Logs",
        "clear_logs_confirm": "Clear logs for account {name}?",
        "clear_logs_success": "Logs cleared",
        "clear_logs_failed": "Failed to clear logs",
        "qr_expired_not_found": "QR expired or not found",
        "qr_login_failed": "QR login failed",
        "qr_status_failed": "Failed to get QR status",
        "qr_password_required": "2FA password required",
        "qr_password_missing": "Please enter your 2FA password",
        "qr_password_invalid": "Incorrect 2FA password",
        "qr_password_submit": "Submit Password",
        "account_name_placeholder": "e.g. Work_Account_01",
        "phone_number_placeholder": "+86 138 0000 0000",
        "qr_alt": "QR Code",
        "task_deleted": "Task {name} deleted",
        "task_run_failed": "Task run failed",
        "task_run_success": "Task {name} running",
        "account_name_prompt": "Please enter account name",
        "status_active": "Active",
        "status_paused": "Paused",
        "task_schedule": "Schedule",
        "task_channels": "Channels",
        "task_hits": "{count} Hits",
        "task_last_run": "Last Run",
        "task_run_logs_title": "Task Logs: {name}",
        "task_monitor_title": "Task Monitor: {name}",
        "task_monitor_status": "Status",
        "task_monitor_summary": "Latest Summary",
        "task_monitor_messages_tab": "Messages",
        "task_monitor_no_messages": "No structured message events yet",
        "task_message_event_sent": "Message sent",
        "task_message_event_received": "Message received",
        "task_message_event_edited": "Message edited",
        "task_history_logs": "Task History",
        "task_history_logs_title": "Task History: {name}",
        "task_history_empty": "No historical execution logs",
        "task_history_no_messages": "No structured message events for this run (older record or no reply received)",
        "task_history_no_flow": "No detailed flow for this record (older versions may only keep result)",
        "task_history_truncated": "Log was truncated. Original lines: {count}",
        "logs_waiting": "Waiting for logs...",
        "task_running": "Running...",
        "task_done": "Task completed",
        "task_executing": "Executing...",
        "chats_refreshed": "Chat list refreshed",
        "refresh_failed": "Refresh failed",
        "search_failed": "Search failed",
        "chat_id_numeric": "Chat ID must be a number",
        "update_success": "Task updated",
        "update_failed": "Update failed",
        "chat_default_name": "Chat {id}",
        "form_incomplete": "Please fill in all information",
        "username_changed": "Username changed successfully",
        "change_failed": "Failed to change",
        "password_mismatch": "Passwords do not match",
        "password_changed": "Password changed successfully",
        "setup_failed": "Setup failed",
        "two_factor_enabled": "2FA enabled",
        "enable_failed": "Enable failed",
        "two_factor_disable_prompt": "Enter 2FA code to disable:",
        "two_factor_disabled": "2FA disabled",
        "disable_failed": "Disable failed",
        "export_success": "Config exported",
        "export_failed": "Export failed",
        "import_empty": "Please paste config",
        "import_success": "Import successful",
        "import_failed": "Import failed",
        "ai_save_success": "AI config saved",
        "connect_failed": "Connect failed",
        "test_failed": "Test error",
        "confirm_delete_ai": "Are you sure you want to delete AI config?",
        "ai_delete_success": "AI config deleted",
        "global_save_success": "Global settings saved",
        "telegram_save_success": "Telegram config saved",
        "confirm_reset_telegram": "Are you sure you want to reset Telegram config to default?",
        "config_reset": "Config reset",
        "operation_failed": "Operation failed",
        "new_username_placeholder": "New Username",
        "current_password_placeholder": "Verify Current Password",
        "status_enabled": "ENABLED",
        "status_disabled": "DISABLED",
        "totp_code_placeholder": "6 digits",
        "delete_ai_config": "Delete AI config",
        "ai_base_url_placeholder": "https://api.openai.com/v1",
        "api_key_keep_hint": "Leave empty to keep the current API key",
        "sign_interval_placeholder": "Leave blank for random 1-120 seconds",
        "data_dir": "Data Directory",
        "data_dir_placeholder": `e.g. ${BRAND_DATA_DIR_EXAMPLE}`,
        "data_dir_desc": "Used for sessions, logs, database, and task files",
        "data_dir_restart_hint": "Restart backend service to apply changes",
        "tg_api_id_placeholder": "From my.telegram.org",
        "tg_api_hash_placeholder": "From my.telegram.org",
        "telegram_notification_config": "Telegram Bot Notifications",
        "telegram_notification_desc": "Configure an official Telegram Bot for task completion messages. The global setting acts as the default target, and each account can override or disable it in the edit dialog.",
        "notification_bot_token": "Bot Token",
        "notification_bot_token_placeholder": "123456:ABC-DEF",
        "notification_bot_token_keep_hint": "Leave blank and keep the option checked to preserve the current Bot Token",
        "notification_chat_id": "Chat ID",
        "notification_chat_id_placeholder": "e.g. -1001234567890",
        "notification_keep_existing_token": "Keep existing token",
        "telegram_notification_save_success": "Telegram notification config saved",
        "telegram_notification_test_success": "Test message sent. Check Telegram.",
        "telegram_notification_test_failed": "Failed to send test message",
        "confirm_delete_telegram_notification": "Are you sure you want to delete the Telegram notification config?",
        "telegram_notification_delete_success": "Telegram notification config deleted",
        "delete_notification_config": "Delete notification config",
        "test_send": "Send test message",
        "task_notification": "Task Completion Notifications",
        "notification_follow_global": "Use global",
        "notification_custom": "Custom",
        "notification_disabled": "Disabled",
        "github_repo": "GitHub Repository",
        "unknown_sender": "Unknown sender",
        "unknown_chat": "Unknown chat",
        "totp_placeholder": "Skip if disabled",
        "switch_to_english": "Switch to English",
        "switch_to_chinese": "Switch to Chinese",
        "switch_to_light": "Switch to Light Mode",
        "switch_to_dark": "Switch to Dark Mode"
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLangState] = useState<Language>('zh');
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        const savedLang = localStorage.getItem('tg-signer-lang') as Language;
        if (savedLang) {
            setLangState(savedLang);
        }
        setMounted(true);
    }, []);

    const setLanguage = (lang: Language) => {
        setLangState(lang);
        localStorage.setItem('tg-signer-lang', lang);
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    if (!mounted) return null;

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
